name = "tasks_sample"
description = "A simple program to demonstrate tasking."
version = "0.1.0-dev"

authors = ["Peter Chapin"]
maintainers = ["Peter Chapin <spicacality@kelseymountain.org>"]
maintainers-logins = ["pchapin"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["tasks_sample"]
