name = "huffman_sample"
description = "A sample Huffman encoding program."
version = "0.1.0-dev"

authors = ["Peter Chapin"]
maintainers = ["Peter Chapin <spicacality@kelseymountain.org>"]
maintainers-logins = ["pchapin"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["huffman_sample"]
